sudo: required
language: generic

services:
  - docker

before-install:
  - docker build -t saleemv/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true saleemv/docker-react npm run test -- --coverage
